### ISSUE TITLE
BT does hang on first start - ungoogled/safe mode available?

### ISSUE THREAD

**Issue by chymian** [tconfrey/BrainTool#24]
hi @tconfrey 

on my the quest for a reasonable mgmt-tool I reached BT today. unfortunatley it does not work at all with ungoogled chromium running on debian/KDE.

starting the topic-manager hangs on
`Loading your BrainTool file`

no buttons are working within, like settings, actions, help etc

I reinstalled the extension with no change.

Browser: Version 104.0.5112.102 (Official Build, ungoogled-chromium) built on Debian bullseye/11, 
running on Debian bullseye/11 (64-Bit)

### Thesis
all revenue-driven companys spy on you & your data and sell them without your consent. 
which is proofen many times!

Is this tool for security aware People?
1) since I read, that it's quite close entangled with google-account/drive, is it ment to run in an ungoogled/private workspace?
2) is there a data-safe mode, which uses open-source alternatives to google? like useing selfhosted cloudspace, i.e. NextCloud, WebDav, S3-bucktes, etc?
3) can you please move your discussion-group to a site where one hast not to sign up with BigTech to participate?

**Comment by azizLIGHT** [comment]
I was having the same issue with BrainTool hanging on first start and showing `Loading your BrainTool file` but this was on regular Chrome 109 on Windows 10 x64, not ungoogled that much. 

In my case, disabling my privacy extension LocalCDN fixed the issue. If you're using other extensions that intercept or modify requests, try disabling those extensions and trying. Next, try running ungoogled-chromium with a blank user profile and no other extensions except BrainTool to verify more.

**Comment by tconfrey** [comment]
Hi,
Apologies for not replying til now. I recently started working on BrainTool again to get it to a 1.0 version compliant with Googles new mandated MV3 extension infrastructure.

The hanging issue should be long fixed. There was a bug related to restoring the position of the Topic Manager that happened mostly with multiple displays. The browser could throw an error about the position and since it was not handled the popup just hung. 

I understand the points about data privacy and see it as a big plus for BrainTool. You can now sync and export to a local file, no need for a google account. The code is all available on this repo and your data never leaves your machine (unless you set up GDrive syncing).
