### ISSUE TITLE
BrainTool managed web page as tab instead of window (and, a few words about basic use)

### ISSUE THREAD

**Issue by fgilbert68** [tconfrey/BrainTool#6]
First of all, as an intensive Emacs+Org-mode user, I am enthusiastic about this project.
Nonetheless, I really struggled with the basic use of the plugin. Even after allowing the Google Drive access, first nothing happened when pressing `=M-b=`. Then all of a sudden there was this dialog box allowing to type in a tag and comment. But it is not obvious how to validate what you have entered, and as I had the bad idea to have a look at something else while the dialog box was open, I had the bad surprise going back to the web page, that the dialog box was closed, and the few words I had typed in were lost.
So, maybe you should write some basic instructions about how your tool is supposed to be used. Maybe this is obvious for you, but maybe not for everybody...

But the main problem for me with BrainTool is that, if a page is "managed" by BrainTool, it then opens in a new window. I would like to be able to open it as a new tab in the current window (that's how I work, one full screen window and a lot of tabs inside it, sometimes using the new tabs grouping functionality). If I ask the new window to join the existing main window with the other tabs, obviously the link with BrainTool is lost. That alone will make it hard for me to use your plugin.

**Comment by tconfrey** [comment]
Hi @fgilbert68 ,
Thanks for the comment and apologies for only finding it today! I had not been monitoring github for issues reported here.

Yes better documentation is key! I have updated material since you opened this issue so things are a bit better.

WRT windowing, that has been my major focus recently. I have a new version with options for tag to window mappings. I'll have a version out to beta testers early next week (I'll put a post up on the [discussion group](https://groups.google.com/u/2/g/braintool-discussion) and you can LMK if you want early access).

Cheers,
Tony

**Comment by tconfrey** [comment]
Hi @fgilbert68 ,
The 0.7.0 version of BrainTool, live on the Web Store today, supports three ways of mapping tagged urls to windows and tabs. 
- 'Window' is the original model whereby urls with a given tag are opened in a dedicated window. 
- 'Tab Groups' uses Chrome's tab grouping mechanism to open urls with the same tag in a tab group with potentially many tab groups per window. 
- 'None' is probably the one you want, it ignores windows and just opens tabs in the default working window.

LMK if you have any feedback on this model.

**Comment by fgilbert68** [comment]
Thanks a lot tconfrey!
I tried it and I like it. I will start using the extension for real now -- and it is much simpler and practical than fiddling with org-capture.
